baseURL = 'http://example.org/'
languageCode = 'zh-cn'
title = "IAKSH's Archive"
theme = 'github-style'

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
    author = "Lain"
    description = "ni hao."
    github = "IAKSH"
    email = "021askmenot@gmail.com"
    url = "dont have a server yet"
    keywords = "blog"
    rss = true
    lastmod = true
    userStatusEmoji = "😜"
    favicon = "/images/github.png"
    avatar = "/images/avatar.png"
    headerIcon = "/images/GitHub-Mark-Light-32px.png"
    location = "China"
    enableGitalk = false

    [params.gitalk]
        clientID = "Your client ID"
        clientSecret = "Your client secret"
        repo = "repo"
        owner = "MeiK2333"
        admin = "MeiK2333"
        id = "location.pathname"
        labels = "gitalk"
        perPage = 15
        pagerDirection = "last"
        createIssueManually = true
        distractionFreeMode = false
    [[params.links]]
        title = "Them Author"
        href = "https://meik2333.com"
        icon = "https://meik2333.com/images/avatar.png"

    [frontmatter]
        lastmod = ["lastmod", ":fileModTime", ":default"]